name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - run: npm i -g @antfu/ni
      - run: pnpm install
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: pnpm run build
      - run: npx @vscode/vsce publish -p ${{secrets.VSCE_TOKEN}} --no-dependencies
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
      # - run: cd dist && npx ovsx publish -p ${{secrets.OVSX_TOKEN}} --no-dependencies
      #   env:
      #     OVSX_TOKEN: ${{secrets.OVSX_TOKEN}}
